---
- name: Apply local role for testing
  hosts: all

  vars:
    localTesting: true

  roles:
    - role: "{{ playbook_dir }}"
    - {
        role: degoss,
        goss_file: tests/goss/blender.yml
    }